[project]
name = "elora"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "feedparser>=6.0.12",
    "kokoro-onnx>=0.5.0",
    "ollama>=0.6.2",
    "playwright>=1.61.0",
    "requests>=2.34.2",
    "soundfile>=0.14.0",
    "vosk>=0.3.45",
]
